//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 03:35:08 AM PST 
//


package com.his.ar.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.his.ar.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.his.ar.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IndvDetailRequest }
     * 
     */
    public IndvDetailRequest createIndvDetailRequest() {
        return new IndvDetailRequest();
    }

    /**
     * Create an instance of {@link IndvDetailResponse }
     * 
     */
    public IndvDetailResponse createIndvDetailResponse() {
        return new IndvDetailResponse();
    }

    /**
     * Create an instance of {@link IndvDetailType }
     * 
     */
    public IndvDetailType createIndvDetailType() {
        return new IndvDetailType();
    }

}
